var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/chat/route.js")
R.c("server/chunks/node_modules_@vercel_oidc_dist_0u5k4yl._.js")
R.c("server/chunks/node_modules_next_dist_13e8ckn._.js")
R.c("server/chunks/node_modules_zod_v4_core_12ucq-s._.js")
R.c("server/chunks/node_modules_zod_v4_classic_1aknt7v._.js")
R.c("server/chunks/node_modules_zod_v4_locales_15gcos7._.js")
R.c("server/chunks/node_modules_@ai-sdk_provider-utils_dist_index_1afcz0a.js")
R.c("server/chunks/node_modules_@ai-sdk_gateway_dist_index_17y7wk2.js")
R.c("server/chunks/node_modules_ai_dist_index_16zsbns.js")
R.c("server/chunks/node_modules_0vwxzdz._.js")
R.c("server/chunks/[root-of-the-server]__1gpm0zq._.js")
R.c("server/chunks/_next-internal_server_app_api_chat_route_actions_1d_pld-.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/chat/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/chat/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
