var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/badge/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__17yjzh5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0l75snu._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xpcv9w._.js")
R.c("server/chunks/ssr/app_layout_tsx_2144vk_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_badge_page_actions_1yqx7ex.js")
R.m(92947)
module.exports=R.m(92947).exports
